### ISSUE TITLE
OdbcConstants.pqm not found on PowerBI Desktop Windows 10

### ISSUE THREAD

**Issue by SDonatas** [belyaevvo/ClickHouseConnector#4]
On windows 10 have installed PowerBI, did full setup of ODBC which works for import only. Also used your connector following instructions. Was able to launch connector within UI, but during a configuration flow and selection of directQuery, at some point received an error stating that 'OdbcConstants.pqm' File was not found. Tried changing path within ClickHouseConnector.pq file last line ODBC = Extension.LoadFunction("OdbcConstants.pqm") but it did not have any affect. Any ideas how to solve this?

Exact Error:
We encountered an error while trying to connect
Details: "We couldn't find the file OdbcConstants.pqm"

**Comment by belyaevvo** [comment]
I think you need to download .mez file from release section not a source .pq files

**Comment by SDonatas** [comment]
Ok Thanks for your response. Will give it a try.

**Comment by SDonatas** [comment]
It all worked. Could you confirm whether clickhouse connector should also work on the published powerBI reports to the web, i.e. web powerbi published reports should be able to query data live from clickhouse?

**Comment by belyaevvo** [comment]
As far as I know microsoft only allows certified connectors to run in
powerbi cloud. So your only option is to use on-premises data gateway to
run custom uncertified connector  Follow the data gateway instructions to
use custom connector with it.

чт, 20 июл. 2023 г., 18:09 Donatas Svilpa ***@***.***>:
