### ISSUE TITLE
i cant  connect my data source to  powerbi.com, this connectoris working in power bi desktop for direct query, but not working in powerbi.com after i publich. even thouugh i have installed on premise gateway still its not getting connected

### ISSUE THREAD

**Issue by Nehal-Chaudhari** [belyaevvo/ClickHouseConnector#7]

**Comment by belyaevvo** [comment]
Please note that there are some  limitations and considerations:
https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors
Please ensure that you have fully complied with all requirements.

On-Premises Gateway machine must have network access to ClickHouse instance and all ClickHouse ODBC drivers installed

**Comment by Nehal-Chaudhari** [comment]
I have ensured that i have fully complied with all the requirements.
I am able to connect with same server and credentials for other connector and standard odbc connector, 
but when I set  connection type to clickhouseodbc which is this one which adding gateway , it throws a error like this 
![Screenshot from 2023-11-24 16-30-29](https://github.com/belyaevvo/ClickHouseConnector/assets/130993075/5ca18162-9088-444b-b423-d535857596f7)

where as on same gateway and same credentials are connectinng for normal odbc.
